# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dc/workspace/monoserv/monoserv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dc/workspace/monoserv/monoserv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dc/workspace/monoserv/monoserv/CMakeFiles /home/dc/workspace/monoserv/monoserv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dc/workspace/monoserv/monoserv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Monoserv

# Build rule for target.
Monoserv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Monoserv
.PHONY : Monoserv

# fast build rule for target.
Monoserv/fast:
	$(MAKE) -f CMakeFiles/Monoserv.dir/build.make CMakeFiles/Monoserv.dir/build
.PHONY : Monoserv/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Monoserv.dir/build.make CMakeFiles/Monoserv.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Monoserv.dir/build.make CMakeFiles/Monoserv.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Monoserv.dir/build.make CMakeFiles/Monoserv.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tcpserver.o: src/tcpserver.cpp.o

.PHONY : src/tcpserver.o

# target to build an object file
src/tcpserver.cpp.o:
	$(MAKE) -f CMakeFiles/Monoserv.dir/build.make CMakeFiles/Monoserv.dir/src/tcpserver.cpp.o
.PHONY : src/tcpserver.cpp.o

src/tcpserver.i: src/tcpserver.cpp.i

.PHONY : src/tcpserver.i

# target to preprocess a source file
src/tcpserver.cpp.i:
	$(MAKE) -f CMakeFiles/Monoserv.dir/build.make CMakeFiles/Monoserv.dir/src/tcpserver.cpp.i
.PHONY : src/tcpserver.cpp.i

src/tcpserver.s: src/tcpserver.cpp.s

.PHONY : src/tcpserver.s

# target to generate assembly for a file
src/tcpserver.cpp.s:
	$(MAKE) -f CMakeFiles/Monoserv.dir/build.make CMakeFiles/Monoserv.dir/src/tcpserver.cpp.s
.PHONY : src/tcpserver.cpp.s

src/threadpool.o: src/threadpool.cpp.o

.PHONY : src/threadpool.o

# target to build an object file
src/threadpool.cpp.o:
	$(MAKE) -f CMakeFiles/Monoserv.dir/build.make CMakeFiles/Monoserv.dir/src/threadpool.cpp.o
.PHONY : src/threadpool.cpp.o

src/threadpool.i: src/threadpool.cpp.i

.PHONY : src/threadpool.i

# target to preprocess a source file
src/threadpool.cpp.i:
	$(MAKE) -f CMakeFiles/Monoserv.dir/build.make CMakeFiles/Monoserv.dir/src/threadpool.cpp.i
.PHONY : src/threadpool.cpp.i

src/threadpool.s: src/threadpool.cpp.s

.PHONY : src/threadpool.s

# target to generate assembly for a file
src/threadpool.cpp.s:
	$(MAKE) -f CMakeFiles/Monoserv.dir/build.make CMakeFiles/Monoserv.dir/src/threadpool.cpp.s
.PHONY : src/threadpool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Monoserv"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tcpserver.o"
	@echo "... src/tcpserver.i"
	@echo "... src/tcpserver.s"
	@echo "... src/threadpool.o"
	@echo "... src/threadpool.i"
	@echo "... src/threadpool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

